version: '3'

services:
  web:
    build: .
    command: nso http-server --listen \[::]:80
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.nxapi-znc.entrypoints: websecure
      traefik.http.routers.nxapi-znc.rule: Host(`${TRAEFIK_HOST:-nxapi.ta.fancy.org.uk}`) && PathPrefix(`/api/znc/`)
      traefik.http.routers.nxapi-znc.tls: true
      traefik.http.services.nxapi-znc.loadbalancer.server.port: 80
    environment:
      DEBUG: '*,-express:*'
      # ZNCA_API_URL: http://znca-api/api/znca
    volumes:
      - data:/data

volumes:
  data:
